### ISSUE TITLE
select vehicle

### ISSUE THREAD

**Issue by karussell** [Janekdererste/gh-maps-react#16]
Select the vehicle used for the routing request. The following options are avaliable "car" "bike" "foot" "hike" "mtb" "racingbike" "scooter" "truck" "small_truck"

The info endpoint of the GH Server gives information about the supported vehicles by this very instance. 

This issue inlcudes: 
- Parsing the supported vehicles from the info endpoint
- Giving the user a way to choose a vehicle for routing from the supported vehicles
- Add the vehicle parameter to the routing request
- Add vehicle parameter to url
-

**Comment by Janekdererste** [comment]
Solved with 8181fb10fffc6392acff3225440a6fd30cea756c, 6b2da4050239865249eb28e45456275f6b74196b and bb2d07727530f3e260c206ad8aad4fbf9a783587
